### ISSUE TITLE
unknown tag jqueryPicker:date

### ISSUE THREAD

**Issue by abhaytalreja** [zoran119/grails-jquery-date-time-picker#2]
When i use the tag as instructed, i get the "unknown tag" on jqueryPicker:date.

Am i missing a step?

However, when i just used the jquery ui datepicker, it works like a charm.

Regards,
Abhay

**Comment by zoran119** [comment]
Did you notice the plugin installing? Can you put a sample project somewhere (github for example) for me to look at?

**Comment by abhaytalreja** [comment]
I think that was a compilation issue, today i tried to use the tag, it works like a charm. Have you created any provision for internationalization of the formats in grails?

**Comment by zoran119** [comment]
Excellent! I tried to reproduce the problem but could not... Unfortunately I have not considered internationalisation. You can customise the formats but you cannot have multiple ones at the same time. If you open a new issue I'll have a look into it when I get a chance.

**Comment by abhaytalreja** [comment]
Hey Zoran,

Hope you doing good. I got the datepicker to work just perfect! However, i
am having issues with the timepicker. Below is a sample code, can you guide
me here..?

_Approach 1_
<jqueryPicker:time name="openTo" id="openTo"
value="${addressInstance?.openTo}" pickerOptions="[hourGrid: '4',
minuteGrid: '10', timeFormat: 'hh:mm tt']"/>
*Problem in approach 1 *- No results

_Approach 2_
<jqueryPicker:time name="openTo" id="openTo"
value="${addressInstance?.openTo}" />

$( "#openTo" ).timepicker({

hourGrid: 4,

minuteGrid: 10,

timeFormat: 'hh:mm tt'

});
_Problem in approach 2_ - timepicker not recognized.

Regards,
Abhay

**Comment by zoran119** [comment]
I just tried approach 1 and it seems to be working fine (copied and pasted your code exactly). Can you have a look if there are any errors in the JavaScript console or if there are any resources which aren't found (404 error for example)?

**Comment by abhaytalreja** [comment]
Didn't see any exception but no effect at all... Although, i just tried to
put this same approach 1 on a new gsp page... it gave me the below error on
jquery.

Uncaught TypeError: Cannot read property 'length' of undefined ----
jquery-1.8.3.min.js:2

Is there any jquery version that it works with?

**Comment by zoran119** [comment]
Can you reproduce the error in a new project and put it up on github for me to have a look? I cannot reproduce it...

**Comment by abhaytalreja** [comment]
Ok, finally after trying a lot, i figured out the problem, for some reason
it is not loading the timepicker. Not sure if i need to add this... But,
once i loaded the add-on timepicker in my applicationRespources.groovy it
worked.

_resource url:'js/jquery-ui-timepicker-addon.js'_

Thanks for all the help and the patience while i was figuring it out.

Regards,

Abhay

**Comment by fstamine** [comment]
Hi guys, i am having a lil problem in here, well even if i change the time format to "timeFormat: 'hh:mm tt']", nothing changes it keeps staying the 24 hours clock system in the form and does not add AM or PM tho, i have added  customPropertyEditorRegistrar(CustomPropertyEditorRegistrar) to the spring resources file, and also changed the config.groovy file to the wanted format where did i mess up ?
thanks
