### ISSUE TITLE
Wonky date selection if yearRange doesn't include current year

### ISSUE THREAD

**Issue by hayseed** [zoran119/grails-jquery-date-time-picker#5]
Using **Grails 2.3.4**, when attaching a datepicker to a form I'm noticing some weirdness with the actual dates presented and selected.

With the included options, the calendar that is displayed shows January 1990 as the month and year when it is first opened. The **Next Month** arrow is disabled, clicking the **Previous Month** arrow will take you to December 2013.

Selecting any day within the initially displayed month will result in a date being chosen from the month within current year, not the displayed year.

![initial-date](https://f.cloud.github.com/assets/5688214/1875317/97cf636a-78ef-11e3-9e87-f93cbb84d233.png)
![resulting-date](https://f.cloud.github.com/assets/5688214/1875319/b7fa1496-78ef-11e3-9efb-67a64ed762db.png)

As far as I can tell, it's actually displaying the current date, but since it is outside its year range, it's looping back around for the year display.

As soon as the **yearRange** is increased to include the current year the problem disappears.

Tag used is as follows:

``` gsp
<jqueryPicker:date name="dateOfBirth" value="${application?.dateOfBirth}" pickerOptions="[changeMonth: true, changeYear: true, yearRange: '\'1990:2013\'' ]"/>
```

Here's the **Config.groovy**

``` groovy
jqueryDateTimePicker {
    format {
        java {
            datetime = "dd/mm/yyyy HH:mm"
            date = "dd/mm/yyyy"
        }
        picker {
            date = "'dd/mm/yy'"
            time = "'H-mm'"
        }
    }
}
```

**Comment by zoran119** [comment]
It seems to me that `yearRange` only restricts what is displayed in the year dropdown and doesn't affect the month on which the calendar is when opened (that is why clicking on a date inserts a 2014 date into the input).

From the jQuery UI [docs](http://api.jqueryui.com/datepicker/#option-yearRange) (see the last sentence):

> The range of years displayed in the year drop-down: either relative to today's year ("-nn:+nn"), relative to the currently selected year ("c-nn:c+nn"), absolute ("nnnn:nnnn"), or combinations of these formats ("nnnn:-nn"). Note that this option only affects what appears in the drop-down, to restrict which dates may be selected use the minDate and/or maxDate options.

So this behaviour is not specific to this plugin but is how jQuery UI date picker works. Using `minDate` and `maxDate` should provide the desired functionality.
