### ISSUE TITLE
Datepicker not working with dots in the name definition

### ISSUE THREAD

**Issue by darkmoon221** [zoran119/grails-jquery-date-time-picker#6]
When trying to save multiple child domains at one page, it is neccessary to write the name attribute like this:

jqueryPicker:date class="datePicker" name="address[0].street"....
jqueryPicker:date class="datePicker" name="address[1].street"....and so on...

If the name attribute contains dots or braces, the datepicker does not display.

**Comment by klemensz** [comment]
I can confirm this issue.
