### ISSUE TITLE
Possibility to set the time zone

### ISSUE THREAD

**Issue by klemensz** [zoran119/grails-jquery-date-time-picker#7]
It would be great to be able set the time zone of the picker. Now it seems that the component takes the default time zone of the JVM. But in a webapp you can have users from different time zones, so you need to do the offset calculation yourself. I mean when you pass in a Date that is 15:00 Europe/Berlin Summer Time, it will be rendered as 13:00 UTC if the server is set to UTC time zone for example.

**Comment by zoran119** [comment]
Would addition of `timeZone` parameter to the `jqueryPicker:date` and `jqueryPicker:time` work? So it can be used like this:

``` groovy
<jqueryPicker:date name="dateOfBirth" value="${personInstance.dateOfBirth}" timeZone="${TimeZone.getTimeZone('GMT')}" />
```

**Comment by klemensz** [comment]
Yes that should work.
