### ISSUE TITLE
TypeError: $(...).datetimepicker is not a function

### ISSUE THREAD

**Issue by chrismalan** [zoran119/grails-jquery-date-time-picker#9]
It looks as if the jquery-ui-timepicker-addon.js can't be reached.

Here's my BuildConfig.groovy
compile ":jquery-ui:1.10.4"
compile ":jquery-date-time-picker:0.2.0"
runtime ":jquery:1.11.1"

This is from application.js which is loaded into main.gsp
//= require jquery
//= require jquery-ui
//= require timepicker
//= require_tree .
//= require_self

This is the tag: 
<jqueryPicker:time name="startDateAndTime" id="startDateAndTime" value="${happeningInstance?.startDateAndTime}"  />

This is the generated code:
&lt;r:require module="timepicker"/&gt;
script tag here
    $('#startDateAndTime').datetimepicker({
        dateFormat:'dd/mm/yy', timeFormat:'HH:mm'
    });
end of script tag
&lt;input type="text" name="startDateAndTime" id="startDateAndTime"   /&gt;
Only a non-responsive text input is generated.  On reloading and opening the Javascript console I get only the TypeError: $(...).datetimepicker is not a function, as above.

Where have I gone wrong?

**Comment by zoran119** [comment]
I haven't checked, but I haven't updated this plugin to use `asset pipeline` plugin (still uses `resources`). I'd say that is why the `.js` file cannot be found.

**Comment by monksy** [comment]
Chrismalan: This is because you don't have the resources plugin configured, included in the buildconfig, and r:require module='jquery-ui' in your layout.

**Comment by chrismalan** [comment]
Thanks for this.

**Comment by monksy** [comment]
No worries, I ran into the same issue.
